workspace:
  base: /tmp
  path: html

services:
  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
      - HOME=/tmp
      - DOCUMENT_ROOT=/tmp/html
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome:3
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - VNC_NO_PASSWORD=1

pipeline:
  composer-install:
    group: prepare
    image: fpfis/php71-dev
    volumes:
      - /cache:/cache
    environment:
      - DOCUMENT_ROOT=/tmp/html
    commands:
      - composer global require hirak/prestissimo --ansi --no-suggest --no-progress
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: prepare-update-lowest
    image: fpfis/php71-dev
    volumes:
      - /cache:/cache
    environment:
      - DOCUMENT_ROOT=/tmp/html
    commands:
      # @todo remove "composer install" step once the following issue is fixed.
      # @link https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer global require hirak/prestissimo --ansi --no-suggest --no-progress
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  test-grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  test-phpunit:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - chown -R www-data /tmp/html/build/sites
      - find /tmp/html/build/sites/default/files -type d -exec chmod 775 {} \;
      - find /tmp/html/build/sites/default/files -type f -exec chmod 664 {} \;
      - su -s /bin/bash -c "./vendor/bin/phpunit" www-data

  test-behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - chown -R www-data /tmp/html/build/sites
      - find /tmp/html/build/sites/default/files -type d -exec chmod 775 {} \;
      - find /tmp/html/build/sites/default/files -type f -exec chmod 664 {} \;
      - su -s /bin/bash -c "./vendor/bin/behat --strict" www-data

matrix:
  COMPOSER_BOUNDARY:
    - highest
    - lowest
