<?php

/**
 * @file
 * The OpenEuropa Media Gallery Test module file.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_media_gallery_test_media_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Print the view mode so we can assert in the test.
  $view_mode = $build['#view_mode'];
  $build['view_mode'] = [
    '#markup' => t('View mode: @view_mode', ['@view_mode' => $view_mode]),
  ];
}
