<?php

/**
 * @file
 * The module file.
 */

declare(strict_types=1);

use Drupal\media\MediaInterface;

/**
 * Implements hook_entity_type_alter().
 */
function oe_media_circabc_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface $media */
  $media = $entity_types['media'];
  $media->addConstraint('CircaBcDocumentMedia');
  $constraints = $media->getConstraints();
  unset($constraints['DocumentMedia']);
  $media->setConstraints($constraints);
}

/**
 * Implements hook_ENTITY_TYPE_presave() for the Media entity.
 */
function oe_media_circabc_media_presave(MediaInterface $media) {
  if ($media->bundle() !== 'document' || !$media->isDefaultTranslation()) {
    return;
  }

  $type = $media->get('oe_media_file_type')->value;
  if ($type !== 'circabc') {
    return;
  }

  $uuid = $media->get('oe_media_circabc_reference')->uuid;
  if (!$uuid) {
    // We cannot save a media without a UUID.
    throw new \Exception('Missing UUID');
  }

  /** @var \Drupal\oe_media_circabc\CircaBc\CircaBcDocument $document */
  $document = \Drupal::service('oe_media_circabc.client')->getDocumentByUuid($uuid);
  if (!$document) {
    throw new \Exception('There was a problem retrieving the CircaBC document');
  }

  if (!in_array($document->getLangcode(), array_keys(\Drupal::languageManager()->getLanguages()))) {
    throw new \Exception(sprintf('The CircaBC document has an incorrect language code: %s', $document->getLangcode()));
  }

  if ($document->getLangcode() !== $media->language()->getId() && $media->isNew()) {
    $media->set('langcode', _oe_media_circabc_get_drupal_langcode($document->getLangcode()));
  }

  // Clear the remote or local field values in case the user switched from a
  // local or remote media to CircaBC.
  foreach ($media->getTranslationLanguages(TRUE) as $language) {
    $translation = $media->getTranslation($language->getId());
    if (!$translation->get('oe_media_file')->isEmpty()) {
      $translation->set('oe_media_file', []);
    }
    if (!$translation->get('oe_media_remote_file')->isEmpty()) {
      $translation->set('oe_media_remote_file', []);
    }
  }

  \Drupal::service('oe_media_circabc.document_mapper')->mapDocumentMedia($document, $media);
}

/**
 * Returns the Drupal langcode from a CircaBC langcode.
 *
 * In CircaBC, we only have the EU languages so the only exception is PT.
 *
 * @param string $langcode
 *   The CircaBC langcode.
 *
 * @return string
 *   The Drupal langcode.
 */
function _oe_media_circabc_get_drupal_langcode(string $langcode): string {
  if ($langcode === 'pt') {
    return 'pt-pt';
  }

  return $langcode;
}

/**
 * Returns the CircaBC langcode from a Drupal langcode.
 *
 * In CircaBC, we only have the EU languages so the only exception is PT.
 *
 * @param string $langcode
 *   The Drupal langcode.
 *
 * @return string
 *   The CircaBC langcode.
 */
function _oe_media_circabc_get_circabc_langcode(string $langcode): string {
  if ($langcode === 'pt-pt') {
    return 'pt';
  }

  return $langcode;
}
