<?php

/**
 * @file
 * OpenEuropa Media Embed module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ckeditor_css_alter().
 */
function oe_media_embed_ckeditor_css_alter(&$css, $editor) {
  $css[] = drupal_get_path('module', 'oe_media_embed') . '/css/ckeditor_embed.css';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the entity view display edit form for Media entities to add an element
 * that allows to select which view modes can be used for embedding in the
 * WYSIWYG.
 */
function oe_media_embed_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  // We only care about media entities.
  if ($entity->getTargetEntityTypeId() !== 'media') {
    return;
  }
  // We only add to the Custom Display Settings, if it exists.
  if (!isset($form['modes'])) {
    return;
  }

  // Gather which view displays are currently available.
  $options = [];
  $default_value = [];
  foreach (_oe_media_embed_get_enabled_display_options($entity) as $id => $details) {
    $options[$id] = $details['label'];
    $default_value[$id] = $details['embeddable'] ? $id : 0;
  }
  $form['modes']['embeddable_displays'] = [
    '#type' => 'checkboxes',
    '#title' => t('Embedable view displays'),
    '#description' => t('Select which of the view modes should be available when embedding a media entity.'),
    '#options' => $options,
    '#default_value' => $default_value,
  ];

  $form['actions']['submit']['#submit'][] = '_oe_media_embed_save_embeddable_displays';
}

/**
 * Custom submit method for entity view display edit forms.
 *
 * We store whether an entity view display should be embeddable or not.
 */
function _oe_media_embed_save_embeddable_displays(array &$form, FormStateInterface $form_state) {
  if (!$form_state->getValue('embeddable_displays')) {
    return;
  }
  $display = $form_state->getFormObject()->getEntity();
  foreach ($form_state->getValue('embeddable_displays') as $mode => $value) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = \Drupal::entityTypeManager()->getStorage($display->getEntityTypeId())->load($display->getTargetEntityTypeId() . '.' . $display->getTargetBundle() . '.' . $mode);
    // Only save if the value has changed.
    if ($view_display->getThirdPartySetting('oe_media_embed', 'embeddable') !== $value) {
      $view_display->setThirdPartySetting('oe_media_embed', 'embeddable', $value);
      $view_display->save();
    }
  }

}

/**
 * Returns the available entity view displays and if they are embeddable or not.
 *
 * @param \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display
 *   The display being edited.
 *
 * @return array
 *   A list of enabled view displays.
 */
function _oe_media_embed_get_enabled_display_options(EntityViewDisplayInterface $display) {
  $available_options = [];
  // Retrieve all available displays for the target entity type.
  $available_display_modes = \Drupal::service('entity_display.repository')->getViewModeOptions($display->getTargetEntityTypeId());
  foreach ($available_display_modes as $mode => $label) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = \Drupal::entityTypeManager()->getStorage($display->getEntityTypeId())->load($display->getTargetEntityTypeId() . '.' . $display->getTargetBundle() . '.' . $mode);
    if ($view_display && $view_display->status()) {
      $available_options[$mode] = [
        'label' => $label,
        'embeddable' => $view_display->getThirdPartySetting('oe_media_embed', 'embeddable'),
      ];
    }
  }
  return $available_options;
}
