<?php

/**
 * @file
 * OpenEuropa Media Gallery module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_single_element_WIDGET_TYPE_form_alter().
 *
 * Alter the link list widget configuration for the Media Gallery bundle.
 */
function oe_media_gallery_field_widget_single_element_link_list_configuration_form_alter(&$element, FormStateInterface $form_state, $context) {
  if ($context['items']->getEntity()->bundle() !== 'gallery') {
    return;
  }

  $element['link_display']['size']['#access'] = FALSE;
  $element['link_display']['more']['#access'] = FALSE;
}
